services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FILES_DIR=/app/uploads